### ISSUE TITLE
Error in turn count in game BreakLock

### ISSUE THREAD

**Issue by LockDown-Ammo** [LockDown-Ammo/GamesBot#12]
Turn count of embed is updated after one interaction that is it is delayed until a user pressed another button which should not happen.

**Comment by 05-Arnav-Gupta** [comment]
Hi ! I am looking into this issue probably caused due to wrong order of code execution due to asynchronous functions.

**Comment by 05-Arnav-Gupta** [comment]
We can clearly find an issue in breakLock.ts line 103.
The increment of turn count is executed after the embed has been constructed!

https://github.com/LockDown-Ammo/GamesBot/blob/04d695310444665166779f8c57b7d4d195eb5b12/src/games/breaklock.ts#L102-L103

So interchanging the line should solve it!
